name: iOS Tests

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.app || sudo xcode-select -s /Applications/Xcode.app

      - name: Resolve Swift packages
        run: |
          xcodebuild -resolvePackageDependencies \
            -project BetterUntis.xcodeproj

      - name: Run unit tests
        run: |
          set -o pipefail
          xcodebuild \
            -project BetterUntis.xcodeproj \
            -scheme BetterUntis \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0' \
            clean test | tee xcodebuild.log
        env:
          NSUnbufferedIO: "YES"

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: xcode-test-logs
          path: xcodebuild.log
